export const TEXT = {
  lang: "es",
  subtitle: "Adivina la palabra agregando vocales.",
  startTitle: "Configurar partida",
  players: "Cantidad de jugadores",
  time: "Tiempo máximo por turno (segundos)",
  rounds: "Rtot — rondas de pistas antes de revelar",
  categoriesTitle: "Categorías",
  randomCategories: "Elegir al azar",
  categoryCount: "Selecciona las categorías que entrarán en juego.",
  startGame: "Comenzar partida",
  selectCategories: "Debes seleccionar exactamente {n} categorías.",
  round: "Ronda",
  turn: "Turno de",
  seconds: "seg",
  boardTitle: "Palabras descubiertas",
  guessPlaceholder: "Escribe la palabra",
  guessPartPlaceholder: "Escribe la palabra {n}",
  categoryPlaceholder: "Elige una categoría",
  guess: "Adivinar",
  correct: "¡Correcto! Palabra y categoría.",
  wordOnly: "Has acertado la palabra, pero no la categoría.",
  categoryOnly: "Has acertado la categoría, pero no la palabra.",
  wordOnlyPoints: "Has acertado la palabra. +{points} puntos.",
  categoryOnlyPoints: "Has acertado la categoría. +{points} puntos.",
  compoundOneOnly: "Has acertado una de las dos palabras. +la mitad del puntaje.",
  compoundWordsButCategory: "Has acertado las dos palabras, pero no la categoría. +{points} puntos.",
  partialPoints: "Acierto parcial. +{points} puntos.",
  incorrect: "No es correcto. Le toca al siguiente jugador.",
  timeout: "Se acabó el tiempo. Le toca al siguiente jugador.",
  hintHelp: "Pista: {help}",
  hintSubcategory: "Subcategoría: {category}",
  hintVowel: "Pista: aparece una vocal.",
  revealed: "La palabra era:",
  computer: "ORDENADOR",
  continue: "Continuar",
  end: "Fin de la partida",
  newGame: "Nueva partida",
  points: "puntos",
  noPoints: "sin puntos",
  player: "Jugador",
  category: "Categoría",
  fortext: "Comentario",
  won: "Ganador",
  tie: "Empate",
  categoryAlready: "Esta categoría ya está seleccionada.",
  noWords: "No hay suficientes palabras válidas en las categorías seleccionadas.",
  specialRound: "El ordenador revela una palabra.",
  remaining: "faltan",
  revealedWord: "Palabra revelada"
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{(\w+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
