export const EMOJI_MAP = {
  "CUORE": "❤️",
  "DIVIETO": "🚫",
  "PROIBITO": "🚫",
  "AMORE": "❤️",
  "AMARE": "❤️"
};

export const TEXT = {
  lang: "it",
  subtitle: "Indovina la parola aggiungendo le vocali.",
  startTitle: "Configura la partita",
  rulesTitle: "Come giocare?",
  rule1: "Scopri le parole nascoste completando le vocali mancanti.",
  rule2: "Le parole di 3 lettere o meno devono corrispondere esattamente.",
  rule3: "Ad ogni turno, seleziona una categoria e scrivi la tua risposta.",
  rule4: "Ottieni punti extra se indovini sia la parola che la categoria.",
  configTitle: "Configurazione Partita",
  sortCategoriesTitle: "Ordina categorie per:",
  sortAlpha: "Alfabetico",
  sortDifficulty: "Difficoltà",
  sortRandom: "Casuale",
  sortTags: "Tag",
  players: "Numero di giocatori",
  playerColorsTitle: "Colori dei giocatori",
  choosePlayerColor: "Scegli il colore per il Giocatore {n}",
  time: "Tempo massimo per turno (secondi)",
  rounds: "Rtot — round di indizi prima di rivelare",
  categoriesTitle: "Categorie",
  randomCategories: "Scegli a caso",
  categoryCount: "Seleziona le categorie che entreranno in gioco.",
  startGame: "Inizia la partita",
  selectCategories: "Devi selezionare esattamente {n} categorie.",
  round: "Round",
  turn: "Turno di",
  seconds: "sec",
  boardTitle: "Parole scoperte",
  guessPlaceholder: "Scrivi la parola",
  guessPartPlaceholder: "Scrivi la parola {n}",
  categoryPlaceholder: "Scegli una categoria",
  guess: "RISPONDI",
  pause: "Pausa",
  resume: "Riprendi tempo",
  correct: "Corretto! Parola e categoria.",
  wordOnly: "Hai indovinato la parola, ma non la categoria.",
  categoryOnly: "Hai indovinato la categoria, ma non la parola.",
  wordOnlyPoints: "Hai indovinato la parola. +{points} punti.",
  categoryOnlyPoints: "Hai indovinato la categoria. +{points} punti.",
  compoundOneOnly: "Hai indovinato una delle due parole. +metà del punteggio.",
  compoundWordsButCategory: "Hai indovinato entrambe le parole, ma non la categoria. +{points} punti.",
  partialPoints: "Successo parziale. +{points} punti.",
  incorrect: "Non è corretto. Tocca al prossimo giocatore.",
  incorrectWordCorrectCategory: "Parola errata, categoria corretta.",
  timeout: "Tempo scaduto. Tocca al prossimo giocatore.",
  hintHelp: "Indizio: {help}",
  hintSubcategory: "Sottocategoria: {category}",
  hintVowel: "Indizio: appare una vocale.",
  revealed: "La parola era:",
  computer: "COMPUTER",
  continue: "Continua",
  end: "Fine della partita",
  newGame: "Nuova partita",
  points: "punti",
  noPoints: "nessun punto",
  player: "Giocatore",
  category: "Categoria",
  fortext: "Commento",
  won: "Vincitore",
  tie: "Pareggio",
  categoryAlready: "Questa categoria è già stata selezionata.",
  noWords: "Non ci sono abbastanza parole valide nelle categorie selezionate.",
  specialRound: "Il computer rivela una parola.",
  remaining: "mancano",
  revealedWord: "Parola rivelata",
  revealedWordContinue: "La parola è stata rivelata. Premi CONTINUA per proseguire.",
  revealedUnansweredTitle: "Parola non indovinata",
  revealCategoryLabel: "Categoria / sottocategoria",
  revealFortextLabel: "Fortext",
  revealWordLabel: "Parola",
  revealHelpLabel: "Aiuto / sinonimo",
  wordBlockCorrect: "Hai indovinato la parola.",
  wordPartialCorrect: "Hai indovinato parte della parola.",
  categoryCorrect: "Hai indovinato la categoria."
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}
