export const EMOJI_MAP = {
  "HEART": "❤️",
  "FORBIDDEN": "🚫",
  "LOVE": "❤️"
};

export const TEXT = {
  lang: "en",
  subtitle: "Guess the word by adding vowels.",
  startTitle: "Setup Game",
  rulesTitle: "How to play?",
  rule1: "Discover hidden words by filling in the missing vowels.",
  rule2: "Words with 3 letters or fewer must match exactly.",
  rule3: "On each turn, select a category and type your guess.",
  rule4: "Earn extra points for matching both the word and the category.",
  configTitle: "Game Settings",
  sortCategoriesTitle: "Sort categories by:",
  sortAlpha: "Alphabetical",
  sortDifficulty: "Difficulty",
  sortRandom: "Random",
  sortTags: "Tags",
  players: "Number of players",
  playerColorsTitle: "Player colors",
  choosePlayerColor: "Choose color for Player {n}",
  time: "Turn time limit (seconds)",
  rounds: "Rtot — hint rounds before reveal",
  categoriesTitle: "Categories",
  randomCategories: "Pick random",
  categoryCount: "Select the categories to play.",
  startGame: "Start Game",
  selectCategories: "You must select exactly {n} categories.",
  round: "Round",
  turn: "Turn of",
  seconds: "sec",
  boardTitle: "Discovered Words",
  guessPlaceholder: "Type the word",
  guessPartPlaceholder: "Type word {n}",
  categoryPlaceholder: "Choose a category",
  guess: "SUBMIT",
  pause: "Pause",
  resume: "Resume time",
  correct: "Correct! Word and category.",
  wordOnly: "Correct word, but wrong category.",
  categoryOnly: "Correct category, but wrong word.",
  wordOnlyPoints: "You guessed the word. +{points} points.",
  categoryOnlyPoints: "You guessed the category. +{points} points.",
  compoundOneOnly: "You guessed one of the two words. +half score.",
  compoundWordsButCategory: "You guessed both words, but wrong category. +{points} points.",
  partialPoints: "Partial success. +{points} points.",
  incorrect: "Incorrect. Next player's turn.",
  incorrectWordCorrectCategory: "Wrong word, correct category.",
  timeout: "Time is up. Next player's turn.",
  hintHelp: "Hint: {help}",
  hintSubcategory: "Subcategory: {category}",
  hintVowel: "Hint: a vowel appears.",
  revealed: "The word was:",
  computer: "COMPUTER",
  continue: "Continue",
  end: "Game Over",
  newGame: "New Game",
  points: "points",
  noPoints: "no points",
  player: "Player",
  category: "Category",
  fortext: "Comment",
  won: "Winner",
  tie: "Tie",
  categoryAlready: "This category is already selected.",
  noWords: "Not enough valid words in selected categories.",
  specialRound: "The computer reveals a word.",
  remaining: "remaining",
  revealedWord: "Revealed Word",
  revealedWordContinue: "Word revealed. Press CONTINUE to proceed.",
  revealedUnansweredTitle: "Unguessed Word",
  revealCategoryLabel: "Category / subcategory",
  revealFortextLabel: "Fortext",
  revealWordLabel: "Word",
  revealHelpLabel: "Help / synonym",
  wordBlockCorrect: "You guessed the word.",
  wordPartialCorrect: "You guessed part of the word.",
  categoryCorrect: "You guessed the category."
};

export function t(key, vars = {}) {
  let s = TEXT[key] ?? key;
  return s.replace(/\{([a-zA-Z0-9_]+)\}/g, (_, k) => vars[k] ?? `{${k}}`);
}